version: '2'

services: 
  elasticsearch:  
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes: 
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/path/to/logs
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment:
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash-sample.conf:/usr/share/logstash/config/logstash-sample.conf
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/pattern:/usr/share/logstash/pattern
    ports:
      - "5044:5044"
      - "10515:10515"
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    command: logstash -f /usr/share/logstash/config/logstash-sample.conf
    networks:
      - efk
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
